### ISSUE TITLE
Implementar un modo silencio 

### ISSUE THREAD

**Issue by ManuelLR** [SUGUS-GNULinux/minolobot#1]
La idea es poder callarlo durante las conversaciones serias para evitar que moleste. 

La propuesta sería:
- calla @botname
   -  vaaale... 😢
- ahora si @botname
   - Arigatao

**Comment by lupoDharkael** [comment]
en principio se pensaba implementar no en mucho el comando /setactivity para mostrar un teclado y elegir entre habilitar y deshabilitar las interacciones pero se podría considerar esa opción.

**Comment by ManuelLR** [comment]
Debe detectar un calla o cállate y el nombre del bot en el mismo mensaje. 
No implementaría la detección de frases para habilitarlo nuevamente por lo que únicamente se permitiría que siguiese hablando si detecta el /enable true

**Comment by ManuelLR** [comment]
El issue #16 recoge lo comprendido en este issue despreciando lo ya hecho y aportando más detalles sobre lo que queda por hacer.  Por tanto se va a cerrar este issue.
