### ISSUE TITLE
Cambiar, en la licencia, el propietario del código

### ISSUE THREAD

**Issue by ManuelLR** [SUGUS-GNULinux/minolobot#14]
Como propuso @lupoDharkael cambiar el propietario de la licencia a la asociación. Concretamente a **SUGUS GNU/Linux**. 
Por favor, dejar constancia explicita de la aceptación del cambio

**Comment by lupoDharkael** [comment]
Todo mi código aportado al proyecto queda en nombre de la asociación SUGUS GNU/Linux a partir de ahora.
