### ISSUE TITLE
Detectar tildes al callarse

### ISSUE THREAD

**Issue by reyesch** [SUGUS-GNULinux/minolobot#24]

**Comment by ManuelLR** [comment]
Lo que habría que editar sería esta línea:
https://github.com/SUGUS-GNULinux/minolobot/blob/master/interaction/disable.go#L46
Y el método a usar podría ser el siguiente:
https://golang.org/pkg/strings/#EqualFold

Con esto mejoraría en general pero no soluciona el tema de las tildes. Quizás esté artículo podría ayudar y orientar sobre el tema: https://blog.golang.org/normalization
